<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="108" started-at="2019-12-26T17:05:03Z" finished-at="2019-12-26T17:05:03Z">
    <groups>
    </groups>
    <test name="RetryMulitple" duration-ms="108" started-at="2019-12-26T17:05:03Z" finished-at="2019-12-26T17:05:03Z">
      <class name="com.qa.retryFailedTCUsingListener.TestCaseRetryByListerner">
        <test-method status="PASS" signature="Test1ByListerner()[pri:0, instance:com.qa.retryFailedTCUsingListener.TestCaseRetryByListerner@5dfcfece]" name="Test1ByListerner" duration-ms="35" started-at="2019-12-26T17:05:03Z" finished-at="2019-12-26T17:05:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1ByListerner -->
        <test-method status="PASS" signature="Test2ByListerner()[pri:0, instance:com.qa.retryFailedTCUsingListener.TestCaseRetryByListerner@5dfcfece]" name="Test2ByListerner" duration-ms="6" started-at="2019-12-26T17:05:03Z" finished-at="2019-12-26T17:05:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2ByListerner -->
      </class> <!-- com.qa.retryFailedTCUsingListener.TestCaseRetryByListerner -->
    </test> <!-- RetryMulitple -->
    <test name="Test" duration-ms="13" started-at="2019-12-26T17:05:03Z" finished-at="2019-12-26T17:05:03Z">
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
