<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RAM-PC" ignored="1" name="Default test(failed)(failed)" tests="2" failures="2" timestamp="16 Dec 2019 04:59:54 GMT" time="0.099" errors="0">
  <testcase name="softAsset" time="0.029" classname="failed.testCases.TestNGFailedXML">
    <failure type="java.lang.AssertionError" message="expected [20] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [10]
at failed.testCases.TestNGFailedXML.softAsset(TestNGFailedXML.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- softAsset -->
  <testcase name="hardAsset" time="0.005" classname="failed.testCases.TestNGFailedXML">
    <failure type="java.lang.AssertionError" message="expected [11] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [1]
at failed.testCases.TestNGFailedXML.hardAsset(TestNGFailedXML.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- hardAsset -->
  <testcase name="test" time="0.0" classname="failed.testCases.TestNGFailedXML">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- Default test(failed)(failed) -->
